### ISSUE TITLE
How to get multi-view render results?

### ISSUE THREAD

**Issue by haoz19** [DSaurus/threestudio-4dfy#10]
Hi,

Thanks for providing this wonderful work!

How do I get multi-view render results? I ran the code and I got 2 second results with only a front view.

Thanks so much for the help!

**Comment by sherwinbahmani** [comment]
Hi,

There should be a test video when you finish the training. Otherwise you can run the test by changing in the python command from —train to —test and using the stage 3 ckpt. I recommend using the original code base for higher motion btw, this version isn‘t really supported properly.

**Comment by haoz19** [comment]
Thanks for the reply, I did get videos after training, but they only contain 1 view instead of multiple views as shown on the web page.

**Comment by sherwinbahmani** [comment]
The 1 view is usually the validation view. Please try the original code base, it should work fine there.

**Comment by haoz19** [comment]
Thanks! I will try the original code. Could you kindly share some instructions about how I can change the validation view, I want to see the side view. Should I modify the config file or some other files?

**Comment by sherwinbahmani** [comment]
If you increase the number of validation views n_val_views in the config, you should also see side views.

**Comment by haoz19** [comment]
I checked in the config: n_val_views: 4, should I increase it to 8 or even more?

**Comment by haoz19** [comment]
Oh, I got it, if I ran it in test mode, it provided 4 rendering views! Thanks so much for your kind reply!
