### ISSUE TITLE
Error in stage 1: KeyError: 'stable-nerf-volume-renderer'

### ISSUE THREAD

**Issue by r530044129** [DSaurus/threestudio-4dfy#2]
hey, I follow the stage 1 code, but i meet this error, what should i do?
.
dreamer@e9c9125073a7:~/threestudio$ python launch.py --config custom/threestudio-4dfy/configs/fourdfy_stage_1_low_vram.yaml --train --gpu 0 exp_root_dir=zrj_output seed=0 system.prompt_processor.prompt="a dog riding a skateboard"
/home/dreamer/.local/lib/python3.10/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
/home/dreamer/.local/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/dreamer/.local/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/dreamer/.local/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/dreamer/.local/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/dreamer/.local/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)

Import times for custom modules:
   0.1 seconds: custom/threestudio-4dfy

Seed set to 0
Traceback (most recent call last):
  File "/home/dreamer/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 45, in __init__
    self.configure()
  File "/home/dreamer/threestudio/custom/threestudio-4dfy/systems/fourdfy.py", line 44, in configure
    super().configure()
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 290, in configure
    self.renderer = threestudio.find(self.cfg.renderer_type)(
  File "/home/dreamer/threestudio/threestudio/__init__.py", line 13, in find
    return __modules__[name]
KeyError: 'stable-nerf-volume-renderer'

**Comment by DSaurus** [comment]
Hi @r530044129 ,

Sorry for not mentioning how to install stable-nerf-renderer extension. You can follow the instructions on [this website](https://github.com/DSaurus/threestudio-stable-nerf-renderer) to install it.

**Comment by r530044129** [comment]
yeah, it's works now, thanks
