### ISSUE TITLE
About the train time, its quite slow

### ISSUE THREAD

**Issue by r530044129** [DSaurus/threestudio-4dfy#3]
Here is 3090 in win10, I found it quite slow to train, I've spent one hour in 1000 epoch, in low_vram config's stage 1. Is that normal?

Epoch 0: |                                                                           | 1094/? [1:02:51<00:00,  0.29it/s]

**Comment by DSaurus** [comment]
Hi @r530044129 ,

That's interesting. Could you please test the MVDream generation first? I can run 10x faster than you with 3090.

**Comment by r530044129** [comment]
MVDream is quite slow too, eg.:
Epoch 0: |                                                                               | 14/? [05:56<00:00,  0.04it/s]

6 mins just finish 14 epoch, i just use the recommend python code in MVDream test:
```
python launch.py --config custom/threestudio-mvdream/configs/mvdream-sd21.yaml --train --gpu 0 system.prompt_processor.prompt="an astronaut riding a horse"
```

**Comment by r530044129** [comment]
hey, I've tried the MVDream, with default command:
```
python launch.py --config custom/threestudio-mvdream/configs/mvdream-sd21.yaml --train --gpu 0 system.prompt_processor.prompt="a dog riding a skateboard"
```
It's cost about 3.5h to finish 10000 epoch, is that the normal speed?

```
Epoch 0: |                                                                          | 10000/? [3:31:59<00:00,  0.79it/s][INFO] `Trainer.fit` stopped: `max_steps=10000` reached.
Epoch 0: |                                                                          | 10000/? [3:31:59<00:00,  0.79it/s][INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
```
