### ISSUE TITLE
ModuleNotFoundError: No module named 'threestudio-4dfy'                                                                                                    

### ISSUE THREAD

**Issue by Trainingzy** [DSaurus/threestudio-4dfy#4]
Hi, thanks for your great work. 

When I tried to run the code with the following command, the ModuleNotFoundError is raised:
`python launch.py --config custom/threestudio-4dfy/configs/fourdfy_stage_1_low_vram.yaml --train --gpu 0 system.prompt_processor.prompt="a dog riding a skateboard"`

My code structure is as follows:
```
threestudio
   - launch.py
   - custom
      - threestudio-4dfy
         - configs/fourdfy_stage_1_low_vram.yaml
```

**Comment by sherwinbahmani** [comment]
Hi,
Have you tried threestudio at the same level as launch.py and custom?

<img width="299" alt="Screenshot 2023-12-11 at 7 04 12 PM" src="https://github.com/DSaurus/threestudio-4dfy/assets/66998830/04c1e5d9-5c7a-4953-8131-c7aea104832b">

**Comment by Trainingzy** [comment]
> Hi, Have you tried threestudio at the same level as launch.py and custom?
> 
> <img alt="Screenshot 2023-12-11 at 7 04 12 PM" width="299" src="https://private-user-images.githubusercontent.com/66998830/289704432-04c1e5d9-5c7a-4953-8131-c7aea104832b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTkzMDMsIm5iZiI6MTcwMjM1OTAwMywicGF0aCI6Ii82Njk5ODgzMC8yODk3MDQ0MzItMDRjMWU1ZDktNWM3YS00OTUzLTgxMzEtYzdhZWExMDQ4MzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA1MzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZDE0MGE5OWE3ZWNlZGY2ZmQ0MDA2YmFiODZjNzU0NTBjNWFiYjA3YjI1NjJjN2I4OTE3MmRiNWZmNWY2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4yzMc8b8ILQd5WRXY74SmkzEY0NVRab5RKVpO1YeVg">

Hi, thanks for the reply. Yes, the threestudio folder is at the same level as launch.py and custom in my code. 

Now, I solved the problem, but I do not know what causes this....

Specifically, I just set `spawn` as False then it fixed.

![image](https://github.com/DSaurus/threestudio-4dfy/assets/88388847/1428b695-1166-4b3e-9c29-e0196da10d76)

**Comment by DSaurus** [comment]
Hi, @Trainingzy .

I have also encountered the same problem sometimes. I also set 'spawn' to false to resolve it. However, I can't reproduce it anymore even when I set 'spawn' to true. I guess that it might be a problem occurring during the initial loading of the prompt processor.

**Comment by DSaurus** [comment]
I have found that the issues are caused by a conflict in register naming. I plan to address this by implementing a check for all extensions in the coming days.
