### ISSUE TITLE
visualize the result

### ISSUE THREAD

**Issue by yuelei0428** [DSaurus/threestudio-4dfy#5]
Sorry I'm new to threestudio. I was wondering how can we visualize the result after training all the three stages.

I got a checkpoint after the training of stage 3. But how can I use it?

**Comment by DSaurus** [comment]
Hi @yuelei0428 ,

The visualization result is saved to video after training all three stages. You can regenerate the same video by adding `resume=path/to/last.ckpt` after the training script. If you want to change rendering angles, you could modify the code of validation dataset.
