### ISSUE TITLE
 Expected training time

### ISSUE THREAD

**Issue by ZhenWZ** [DSaurus/threestudio-4dfy#6]
What's the expected training time to finish training all the stages?
I spent like 24 hrs, is it usual?

**Comment by sherwinbahmani** [comment]
Hi,

Yeah that is usual if you train stage 3 fully for 100000 iterations, but you can probably abort the training in stage 3 early after 40000 iterations to half the training time without much loss in quality.

**Comment by ZhenWZ** [comment]
Thank you for your reply. 
I also notice that the max steps of trainer in low vram stage 3 are 300000, while the max steps in the usual vram stage 3 are 100000. May I know why?

**Comment by sherwinbahmani** [comment]
You can abort the training for sure after 100000. We will update the configs to set the max to 100000 also for the low vram config. Thanks for noticing this!
