### ISSUE TITLE
Inconsistent appearance along temporal dimension during phase-3

### ISSUE THREAD

**Issue by zqh0253** [DSaurus/threestudio-4dfy#7]
Hi, thanks for your great work.

After phase-3 optimization, I observe changing apperance over time. Here are the results with the prompt "a man walking":

https://github.com/DSaurus/threestudio-4dfy/assets/32608622/191a42bd-a208-45e7-8ecd-59475890b728

https://github.com/DSaurus/threestudio-4dfy/assets/32608622/4fece28a-21be-4020-964b-c928d3b30f15

Here are the results after phase-2, which is used as initialization for phase-3 optimization:

https://github.com/DSaurus/threestudio-4dfy/assets/32608622/0363b71f-58b4-409a-9466-0044208f0147

Do you have any suggestion about this issue?

**Comment by sherwinbahmani** [comment]
Hi,

Sorry for the late reply. Did you use the the low vram config or the normal config? Did you change any of the hyperparameters?

To be honest, I have never encountered this problem.
