### ISSUE TITLE
module missing error

### ISSUE THREAD

**Issue by gganjang** [DSaurus/threestudio-4dfy#9]
I tried to run stage1_low_vram, but encountered an error below:

Traceback (most recent call last):
  File "/home/dreamer/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 51, in __init__
    self.configure()
  File "/home/dreamer/threestudio/custom/threestudio-4dfy/systems/fourdfy.py", line 62, in configure
    self.guidance_multi_view = threestudio.find(
  File "/home/dreamer/threestudio/threestudio/__init__.py", line 37, in find
    return __modules__[name]
KeyError: 'mvdream-multiview-diffusion-guidance'

**Comment by sherwinbahmani** [comment]
Hi,

Did you install the mvdream exension? https://github.com/DSaurus/threestudio-mvdream
It's also mentioned in the README how to install it. You need to install before being able to run this repository, as it uses mvdream as a backbone.

**Comment by gganjang** [comment]
Yes. mvdream is already installed and I did some test runs on it without any problem before trying 4D-fy.

**Comment by sherwinbahmani** [comment]
What's the command you are using? It's not detecting mvdream, which means that it probably wasn't installed to the required location (custom). Make sure that the 4D-fy code can also have access to the mvdream extension.

Does it work running from here: https://github.com/sherwinbahmani/4dfy ?

**Comment by gganjang** [comment]
Problem solved.

Well, I misunderstood the instruction in https://github.com/DSaurus/threestudio-4dfy

Even though mvdream extension(threestudio-mvdream) was alreday installed in 'custom' directory, I was supposed to run 
```
git clone https://github.com/bytedance/MVDream extern/MVDream
pip install -e extern/MVDream
```
in 'custom' directory.

Closing the issue
